{% set name = "kaggle-environments" %}
{% set version = "1.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f8c21499f777fc2f999e1e765bf4afb33f83df5b4e559cd8e06003724a482825

build:
  number: 0
  noarch: python
  entry_points:
    - kaggle-environments = kaggle_environments.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - flask >=1.1.2
    - gym
    - ipython
    - jsonschema >=3.0.1
    - numpy >=1.19.5
    - python >=3.6
    - requests >=2.25.1

test:
  imports:
    - kaggle_environments
  commands:
    - pip check
    - kaggle-environments --help
  requires:
    - pip
    - setuptools

about:
  home: https://github.com/Kaggle/kaggle-environments
  summary: Kaggle Environments
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melonhead901
